# Generated by Django 6.1 on 2026-08-24 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='servicecenter',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='service_center',
        ),
        migrations.RemoveConstraint(
            model_name='autoservice',
            name='unique_service_name_per_center',
        ),
        migrations.AddField(
            model_name='servicecentre',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_centres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='service_centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecentre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='service_centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='services.servicecentre'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='autoservice',
            constraint=models.UniqueConstraint(fields=('service_centre', 'name'), name='unique_service_name_per_centre'),
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='service_center',
        ),
        migrations.DeleteModel(
            name='ServiceCenter',
        ),
    ]
